name: Build Documentation

on:
  push:
    branches:
      - laobiz/ch2016/build-documentation-in-github-actions-directly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v9
    - uses: cachix/cachix-action@v6
      with:
        name: digitallyinduced
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Install OpenSSH
      run: sudo apt install openssh-client -y
    - name: Run SSH script
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 142.93.99.41 >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add <(echo "${{ secrets.KEY }}")
          cd $GITHUB_WORKSPACE
          chmod +x build-haddock
          nix-shell shell.nix --run "./build-haddock; cd Guide; make -B; cd ../ProjectGenerator; make -B"
          echo "Deleting files from server"
          ssh -A root@142.93.99.41 'rm -rf /home/turbohaskell/WebRoot/api-docs; rm -rf /home/turbohaskell/WebRoot/Guide'
          echo "Copying files to server"
          scp -r haddock-build root@142.93.99.41:/home/turbohaskell/WebRoot
          scp -r Guide root@142.93.99.41:/home/turbohaskell/WebRoot
          scp ProjectGenerator/tarball.tar.gz root@142.93.99.41:/home/turbohaskell/WebRoot
          echo "Renaming files"
          ssh -A root@142.93.99.41 'cd /home/turbohaskell/WebRoot; mv haddock-build api-docs; mv tarball.tar.gz ihp-new.tar.gz'
